/**
 * Tabular data-entry drills — the work a DEST or DEO post is actually for.
 *
 * A DEST candidate is not typing prose. They are reading values off a form or a
 * scanned register and entering them field by field: a roll number, a name, a
 * date, an amount, then Tab, then again, six hundred times. The keys involved
 * are the number row and the numpad, the rhythm is Tab-separated bursts rather
 * than flowing sentences, and the whole thing is scored in key depressions.
 *
 * Nothing generated by `generators.ts` rehearses that, so this generates it:
 * a real table, in a shape the exam client uses, with the same field types.
 */

/** A column, and how its values are made. */
interface Column {
  header: string;
  cell: () => string;
}

const FIRST_NAMES = [
  'Rahul', 'Priya', 'Amit', 'Sunita', 'Vikram', 'Anjali', 'Ravi', 'Kavita',
  'Manoj', 'Deepa', 'Sanjay', 'Neha', 'Arun', 'Pooja', 'Suresh', 'Meena',
];
const LAST_NAMES = [
  'Sharma', 'Verma', 'Gupta', 'Singh', 'Yadav', 'Kumar', 'Patel', 'Reddy',
  'Nair', 'Das', 'Joshi', 'Mishra', 'Chauhan', 'Pandey', 'Bose', 'Iyer',
];
const DISTRICTS = [
  'Lucknow', 'Jaipur', 'Bhopal', 'Patna', 'Indore', 'Kanpur', 'Nagpur',
  'Ranchi', 'Raipur', 'Surat', 'Kochi', 'Guwahati', 'Ludhiana', 'Varanasi',
];
const DEPARTMENTS = ['Revenue', 'Health', 'Education', 'Transport', 'Police', 'Rural Dev'];

/**
 * The columns, in the order a register lists them. Chosen so the drill covers
 * the four field types data entry is made of: identifiers (digits), names
 * (letters plus Shift), dates (digits plus separators) and amounts (digits plus
 * a decimal point) — which between them exercise the whole numpad.
 */
const COLUMNS: Column[] = [
  { header: 'Roll No', cell: () => String(randomInt(100000, 999999)) },
  { header: 'Name', cell: () => `${pick(FIRST_NAMES)} ${pick(LAST_NAMES)}` },
  { header: 'District', cell: () => pick(DISTRICTS) },
  { header: 'Department', cell: () => pick(DEPARTMENTS) },
  { header: 'Date', cell: dateCell },
  { header: 'Amount', cell: () => `${randomInt(1000, 99999)}.${pad(randomInt(0, 99), 2)}` },
];

/** Rows a single drill generates — about a minute of work at DEST pace. */
const DEFAULT_ROWS = 14;

export interface DataEntryTable {
  headers: string[];
  rows: string[][];
  /** The table as Tab-separated text — what the typist is scored against. */
  text: string;
  /** Total key depressions the table represents, Tabs and newlines included. */
  depressions: number;
}

/**
 * A table to be copied field by field.
 *
 * Fields are Tab-separated and rows newline-separated, because that is what the
 * real client does and it is what the exam's key-depression count assumes —
 * every Tab is a depression the candidate is credited for.
 */
export function generateDataEntry(rows = DEFAULT_ROWS, columns = COLUMNS): DataEntryTable {
  const headers = columns.map((c) => c.header);
  const cells = Array.from({ length: rows }, () => columns.map((c) => c.cell()));
  const text = cells.map((row) => row.join('\t')).join('\n');
  return {
    headers,
    rows: cells,
    text,
    // Every character is one depression, and the separators are characters.
    depressions: text.length,
  };
}

/** A numeric-only variant, for drilling the numpad alone. */
export function generateNumericEntry(rows = DEFAULT_ROWS): DataEntryTable {
  return generateDataEntry(rows, [
    { header: 'Code', cell: () => String(randomInt(1000, 9999)) },
    { header: 'Quantity', cell: () => String(randomInt(1, 999)) },
    { header: 'Rate', cell: () => `${randomInt(10, 9999)}.${pad(randomInt(0, 99), 2)}` },
    { header: 'Total', cell: () => `${randomInt(100, 99999)}.${pad(randomInt(0, 99), 2)}` },
  ]);
}

function dateCell(): string {
  const day = randomInt(1, 28);
  const month = randomInt(1, 12);
  const year = randomInt(2019, 2026);
  return `${pad(day, 2)}/${pad(month, 2)}/${year}`;
}

function pick<T>(items: T[]): T {
  return items[Math.floor(Math.random() * items.length)] as T;
}

function randomInt(min: number, max: number): number {
  return min + Math.floor(Math.random() * (max - min + 1));
}

function pad(value: number, width: number): string {
  return String(value).padStart(width, '0');
}
